{% set version = "0.7-26" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-maxstat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/maxstat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/maxstat/maxstat_{{ version }}.tar.gz
  sha256: e458c2bb03e3eca09b3b957920e0faba1a50a0d43f6d835a5912f0381fc28b0b

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-exactranktests >=0.8_23    # [build_platform != target_platform]
    - r-mvtnorm >=0.5_10           # [build_platform != target_platform]
  host:
    - r-base
    - r-exactranktests >=0.8_23
    - r-mvtnorm >=0.5_10
  run:
    - r-base
    - r-exactranktests >=0.8_23
    - r-mvtnorm >=0.5_10

test:
  commands:
    - $R -e "library('maxstat')"           # [not win]
    - "\"%R%\" -e \"library('maxstat')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=maxstat
  license: GPL-2.0-or-later
  summary: Maximally selected rank statistics with several p-value approximations.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
