travis:
  secure:
    BINSTAR_TOKEN: Du800ErL7JU9kDbwqXdQfnFvYHCCjGwStmbT2od5YGxVF7G59CswkWzxHX4Dk5J/vCA9E+lE5IgzmGHInpHn2rREkuSJh7QdKaLDY4AaXjLFwlI2InDpDxU3WBPbDIJ31gLh5u8+z0ZsrLXGFp6SA7MCwdJqPTZN2CpaLJBchivHI/hoOoaVrwsY52q9yNylhYZgReSY6SsTWci0mF1JC2Kfhh6cDL+vKeRY5B0n3NXjLmTBMlJCc28wBJGCaEsSblYknWVBENZHNVr8AMBgAYXFd2Obd7xwFzTdccWfs+eAYxCA8SPv3b5yeQ+JSQo+me7mrqCxM1rRlDCzPKTyeF3b9vuoGlqu2/zInMOO/+Ve4vsfvWnZLG8GfHzqsk6GnxhEWCTRPMf/nIc5ZgHVC/6HbHoHuEdvF226V09GG4hNynngEq2Hl+Q4SpVv54jvawoVW8fjYDgPunwBu2sBhwM1kMeVxSS6wzbXm8F4fR99wsgRyawL5aEIckRYisJHqhTff4hTxb0L2ApIlYg5Dv9PKajbPi0J3dxC0aH+9k1wsbR8tmwDWMwun9mfpcSSSRexfKnF2pMfSrZbfE9yf5xHcPMT+RlHJQ7MkKp8vKP1LM+THPTMM/oqw5HgYONocikkxXzVDifUcuM8od51lNJ8icKyuyd+eRcNBnQL0gM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
