travis:
  secure:
    BINSTAR_TOKEN: b/VRCYym3onmBZxzPPcPgt7rFxLfMbfG26KiKymFA9WjRM7UHYztPcrdmRekDHi2jaeGC0xrlzPjGD/LQLnYz5yY8fAmXNPjzkCfWJR5nSe7Qhm32W302k4mR2xPGoeVAW13Ye66cKoRuf2FpFgQRxqCGznS1wGYRt6d0LpjlQ8RAPImG3HtRFF6eoWrlHscGLLiEijHR4HvHZvB8D7ZQ+GStIdbgrGDDJSnMVqWBH8jg19CY3emKnFNeiTRc/0PrJiB44kemjj80w1A9u4JXsxgVq8n1JpwSo+wXzguJY1avNnoo7xbRlIztMZmxKmGnD7zEJZXYjU01d7Fa8PJ0JGPLpvRCO2cJczHq8DF9eOBn9D+lvDbx2676pVrHMJLZYxZHNwOAUvyHjzAVKmdUnR7t9E2E6V/jQZKBvd6KQawClW1UDt0wE5N2r0qOvLFAfXsTe9apFHMtWcO42uoOQY/Rde0NSo9gTHc80idfsbhYCHs/KnguUqBYRJj/b22WsyoTX3tnBSFl8j6rXRois81Z9TxbYvBzyMni1G/t38LGn3wqUD5Y6JOfnKqJTiVHY0bR5jdwVxFYwjm/NYaxkaLYouJoEFS1CjOvbDXnpXQSun3UyigMoA1ZF96NE5wPrZkS2dHfut+2ylrjAbU+Dza4JEJDbAHwqU3XVKANuA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
