appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: xaXF3yyjzpxwkYlFYY1vl14r9BztxRFOl/3+faeCsGgu8hVbJaTEutaIWsvCkip2gPVjmQGKjRjvG2TTO+F8WOKYaOW95V3KqRN6YTnNMDQgoO5RcJRgVS380NiMyDlPrzCV5JbBWn6VaEXhb2c4A27ixvdpzc21mO0OIv/zWZoh7f1+PyKcCo/In/YEIxcMgdWHqV5LVLBgrLbPlCDYzG/3HE/XV52aN4mNqZbgUG4H8kM9wuk0W+s/NG6R0B11V6M00ynZOyxqQL8WXmTjMtXmXJm0G/iYdvZVQVsslm4pc7k8400+LTWGvDbK1+aIU2dotn1An5mUJfuMK/Ev5i8uRcsXW3ut7PWADyl1IF0YLP4x8mmlI5smKJZlNZKn9P3ov1rn9+VxbPyJenc+PFe8nglm8Jw0NFE1meJwe1fxDtfivM8/GDf+IUva225c5qRgQB8p0AXyI377vzarSyHSB1pwtEhbpKzPF4JSpFn6C/c2U2YY7ecULkfoDSLUA4eLXlXaeOH4nhxvbcLZ3QnurOrVKWyxqMrFsph/CYDWcKq+OrkRe9S6aW+y/w49N1aFYENonqfe56gXWdkLPsiCv2NyCBr41S8epDrY4IpSDdcuS2grc+wz7ZTv2tEycjYXj5cv/HJmlwUb7k5Xu/PDeKaf1Zr2cOHGnWoTotc=}
